apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hocs-management-ui
  name: hocs-management-ui
spec:
  maxReplicas: {{.MAX_REPLICAS}}
  minReplicas: {{.MIN_REPLICAS}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hocs-management-ui
  targetCPUUtilizationPercentage: 70
